path: "eval/exp1"
targets:
  x : [0.0, 0.0]
  y : [-1.0, 1.0]
  z : [1.0, 1.0]
lr_pos: 0.005
lr_patch: 0.005
num_hl_iter: 50
num_pos_restarts: 20
num_pos_epochs: 1
num_patch_epochs: 2
batch_size: 32 # TODO: try 16, 32, 64
mode: "split" # fixed, split, joint, hybrid