path: "eval/exp1"
# +x is distance
# +y is left
# +z is top
targets:
  x : [1.0, 1.0]
  y : [-1.0, 1.0]
  z : [0.0, 0.0]
lr_pos: 0.001
lr_patch: 0.001
num_hl_iter: 50
num_pos_restarts: 20
num_pos_epochs: 1
num_patch_epochs: 1
batch_size: 32
mode: "split" # fixed, split, joint, hybrid