path: "eval/debug/settings_test/"
targets:
# +x is distance
# +y is left
# +z is top
  x : [1.0, 0.5]
  y : [-2, null]
  z : [null, null]
lr_pos: 0.005
lr_patch: 0.005
num_hl_iter: 2
num_pos_restarts: 10
num_pos_epochs: 1
num_patch_epochs: 5
batch_size: 32 # TODO: try 16, 32, 64
patch: 
  mode: 'face'  # face, white, random
  path: 'misc/custom_patches/custom_patch_resized.npy' # if mode == 'face' set a path, otherwise path is ignored
mode: "split" # split, joint, hybrid