#path: "eval/debug/random_perspective_10t_q_t/"
path: "eval/debug/ctrl_4/"
# +x is distance
# +y is left
# +z is top
targets:
  x : [ 1.0] #, 1.2, 0.8] #, 1.0] #, 1.0] #, 1.0] #, 1.0, 1.0, 1.0, 1.0, 1.0, 2.0]
  y : [ 0.0] #, 0.0, 0.0] #, -1.0] #, 1.0] #, 0.0] #, 0.0, -1.0, -1.0, 1.0, 1.0, 0.0]
  z : [ 0.0] #, 0.0, 0.0] #, 0.0] #, 0.0] #, -1.0] #, 1.0, -1.0, 1.0, -1.0, 1.0, 0.0]
stlc: # small-time locally controllability
  offsets:
    # base
    - target: [0,0,0]
      position: [0,0,0]
    # x
    - target: [0.1,0,0]
      position: [-0.08,0,0]
    - target: [0.2,0,0]
      position: [-0.12,0,0]
    - target: [-0.1,0,0]
      position: [0.13,0,0]
    - target: [-0.2,0,0]
      position: [0.40,0,0]
    # y
    - target: [0.,0.1,0]
      position: [0,-0.04,0]
    - target: [0,0.2,0]
      position: [0,-0.08,0]
    - target: [0,-0.1,0]
      position: [0,0.04,0]
    - target: [0,-0.2,0]
      position: [0,0.08,0]
    # - target: [0,0.5,0]
    #   position: [0,0.3,0]
    # - target: [0,-0.5,0]
    #   position: [0,-0.3,0]
lr_pos: 0.001
lr_patch: 0.001
prob_weight: 1.0
num_hl_iter: 20
num_pos_restarts: 3
num_pos_epochs: 1
num_patch_epochs: 1
batch_size: 32
num_patches: 1
scale_min: 0.2
scale_max: 0.4
patch: 
  mode: 'random'  # face, white, random
  path: 'src/custom_patches/custom_patch_resized.npy' # if mode == 'face' set a path, otherwise path is ignored
mode: "joint" # fixed, joint, split, hybrid
quantized: true
