batch_size: 32
lr_patch: 0.01
lr_pos: 0.001
mode: joint
num_hl_iter: 50
num_patch_epochs: 1
num_patches: 1
num_pos_epochs: 1
num_pos_restarts: 3
patch:
  mode: random
  path: src/custom_patches/custom_patch_96x160.npy
  size:
  - 80
  - 80
path: results/dataset
prob_weight: 1.0
quantized: false
scale_max: 0.7
scale_min: 0.2
stlc:
  offsets:
  - position:
    - 0
    - 0
    - 0
    target:
    - 0
    - 0
    - 0
targets:
  x:
  - 1.9376560255123456
  - 1.1532584044352152
  y:
  - 0.7505247292610171
  - -0.8387673461395384
  z:
  - 0.1480906420164596
  - 0.3808927727062823
