batch_size: 32
lr_patch: 0.01
lr_pos: 0.001
mode: joint
num_hl_iter: 50
num_patch_epochs: 1
num_patches: 1
num_pos_epochs: 1
num_pos_restarts: 3
patch:
  mode: random
  path: src/custom_patches/custom_patch_96x160.npy
  size:
  - 80
  - 80
path: results/dataset
prob_weight: 1.0
quantized: false
scale_max: 0.7
scale_min: 0.2
stlc:
  offsets:
  - position:
    - 0
    - 0
    - 0
    target:
    - 0
    - 0
    - 0
targets:
  x:
  - 1.3843334058193026
  - 0.8796613673450324
  y:
  - -0.2209451641201441
  - -0.8162580965564461
  z:
  - -0.4992251219438969
  - -0.40751249725507954
