batch_size: 32
lr_patch: 0.01
lr_pos: 0.001
mode: joint
num_hl_iter: 50
num_patch_epochs: 1
num_patches: 1
num_pos_epochs: 1
num_pos_restarts: 3
patch:
  mode: random
  path: src/custom_patches/custom_patch_96x160.npy
  size:
  - 80
  - 80
path: results/dataset
prob_weight: 1.0
quantized: false
scale_max: 0.7
scale_min: 0.2
stlc:
  offsets:
  - position:
    - 0
    - 0
    - 0
    target:
    - 0
    - 0
    - 0
targets:
  x:
  - 0.15279342017583453
  - 1.9319477389904955
  y:
  - 0.19698938989056303
  - -0.16936013874913525
  z:
  - -0.12714041974207957
  - 0.16154212333525375
