batch_size: 32
lr_patch: 0.01
lr_pos: 0.001
mode: joint
num_hl_iter: 50
num_patch_epochs: 1
num_patches: 1
num_pos_epochs: 1
num_pos_restarts: 3
patch:
  mode: random
  path: src/custom_patches/custom_patch_96x160.npy
  size:
  - 80
  - 80
path: results/dataset
prob_weight: 1.0
quantized: false
scale_max: 0.7
scale_min: 0.2
stlc:
  offsets:
  - position:
    - 0
    - 0
    - 0
    target:
    - 0
    - 0
    - 0
targets:
  x:
  - 1.4788244027847381
  - 1.1410296842939782
  y:
  - 0.9537237238792078
  - -0.6262651592645632
  z:
  - -0.3727094477566547
  - -0.1409387393425443
